# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Port

on:
   workflow_dispatch:

jobs:
  Port:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build BrotliPadding.swift
      run: | 
        cd repackfonts
        swiftc -o BrotliPadding.o BrotliPadding.swift
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        
    - name: Install fonttools
      run: python -m pip install fonttools
        
    - name: Run make_woff2src.sh
      run: |
        cd repackfonts
        ./make_woff2src.sh 

